sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master    
notifications:
  email: false
node_js:
  - '4'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.21.3
  - npm i -g npm@^4
before_script:
  - npm prune
script:
  - npm run build
after_success:
  - npm run semantic-release
