sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master    
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm i -g npm@^4
before_script:
  - npm prune
script:
  - npm run build
after_success:
  - git show-ref --head --heads | while IFS=' ' read -r hash name; do test ! -e "${GIT_DIR:-.git}/$name" && echo $hash > "${GIT_DIR:-.git}/$name"; done
  - npm run semantic-release
